BEGIN;

CREATE TABLE IF NOT EXISTS camera_schema_version (
  version INTEGER PRIMARY KEY,
  applied_at_ms BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS camera_tasks (
  task_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  camera_profile TEXT NOT NULL,
  enabled SMALLINT NOT NULL CHECK (enabled IN (0,1)),
  frame_interval_ms INTEGER NOT NULL,
  output_mode TEXT NOT NULL CHECK (output_mode IN ('latest','archive','both')),
  jpeg_quality INTEGER NOT NULL,
  max_width INTEGER NOT NULL,
  max_height INTEGER NOT NULL,
  retention_days INTEGER NOT NULL,
  max_saved_frames INTEGER NOT NULL,
  version INTEGER NOT NULL,
  created_at_ms BIGINT NOT NULL,
  updated_at_ms BIGINT NOT NULL,
  deleted_at_ms BIGINT
);
CREATE INDEX IF NOT EXISTS idx_camera_tasks_updated ON camera_tasks(deleted_at_ms,updated_at_ms DESC);
CREATE TABLE IF NOT EXISTS camera_task_runs (
  run_id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES camera_tasks(task_id),
  definition_version INTEGER NOT NULL,
  definition_json TEXT NOT NULL,
  status TEXT NOT NULL,
  camera_profile TEXT NOT NULL,
  hub_instance_id TEXT,
  create_time_ms BIGINT NOT NULL,
  start_time_ms BIGINT,
  stop_time_ms BIGINT,
  last_update_ms BIGINT NOT NULL,
  worker_consumer TEXT,
  capture_backend TEXT,
  capture_fps DOUBLE PRECISION NOT NULL DEFAULT 0,
  save_fps DOUBLE PRECISION NOT NULL DEFAULT 0,
  consumed_frames BIGINT NOT NULL DEFAULT 0,
  saved_frames BIGINT NOT NULL DEFAULT 0,
  skipped_frames BIGINT NOT NULL DEFAULT 0,
  dropped_frames BIGINT NOT NULL DEFAULT 0,
  last_source_sequence BIGINT NOT NULL DEFAULT 0,
  last_frame_time_ms BIGINT,
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  stop_reason TEXT,
  error_code TEXT,
  error_message TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_camera_task_active_run ON camera_task_runs(task_id)
  WHERE status IN ('queued','starting','running','reconnecting');
CREATE INDEX IF NOT EXISTS idx_camera_runs_task_time ON camera_task_runs(task_id,create_time_ms DESC);
CREATE TABLE IF NOT EXISTS camera_frames (
  frame_id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES camera_tasks(task_id),
  run_id TEXT NOT NULL REFERENCES camera_task_runs(run_id),
  source_sequence BIGINT NOT NULL,
  capture_time_ms BIGINT NOT NULL,
  save_time_ms BIGINT NOT NULL,
  relative_path TEXT NOT NULL UNIQUE,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  size_bytes BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_camera_frames_task_time ON camera_frames(task_id,capture_time_ms DESC);
CREATE INDEX IF NOT EXISTS idx_camera_frames_run_sequence ON camera_frames(run_id,source_sequence);

CREATE TABLE IF NOT EXISTS schema_version (
  version INTEGER PRIMARY KEY,
  applied_time_ms BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS pf_sessions (
  session_id TEXT PRIMARY KEY,
  camera_id TEXT NOT NULL,
  status TEXT NOT NULL,
  start_time_ms BIGINT NOT NULL,
  stop_time_ms BIGINT,
  initial_occupancy BIGINT NOT NULL DEFAULT 0,
  in_count BIGINT NOT NULL DEFAULT 0,
  out_count BIGINT NOT NULL DEFAULT 0,
  final_occupancy BIGINT NOT NULL DEFAULT 0,
  config_version TEXT NOT NULL,
  stop_reason TEXT,
  error TEXT,
  consistency_ok SMALLINT NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_pf_sessions_camera_start ON pf_sessions(camera_id,start_time_ms);
CREATE TABLE IF NOT EXISTS pf_crossing_events (
  event_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES pf_sessions(session_id),
  camera_id TEXT NOT NULL,
  line_id TEXT NOT NULL,
  event_time_ms BIGINT NOT NULL,
  direction TEXT NOT NULL CHECK(direction IN ('IN','OUT')),
  track_id BIGINT NOT NULL,
  confidence DOUBLE PRECISION,
  point_x_norm DOUBLE PRECISION,
  point_y_norm DOUBLE PRECISION,
  evidence_path TEXT,
  config_version TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pf_event_camera_time ON pf_crossing_events(camera_id,event_time_ms);
CREATE INDEX IF NOT EXISTS idx_pf_event_session ON pf_crossing_events(session_id);
CREATE TABLE IF NOT EXISTS pf_aggregates_minute (
  camera_id TEXT NOT NULL,
  bucket_start_ms BIGINT NOT NULL,
  in_count BIGINT NOT NULL DEFAULT 0,
  out_count BIGINT NOT NULL DEFAULT 0,
  occupancy_end BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY(camera_id,bucket_start_ms)
);
CREATE TABLE IF NOT EXISTS pf_calibration_audit (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id TEXT NOT NULL,
  session_id TEXT,
  before_occupancy BIGINT NOT NULL,
  after_occupancy BIGINT NOT NULL,
  reason TEXT NOT NULL,
  operator_name TEXT NOT NULL,
  timestamp_ms BIGINT NOT NULL
);

INSERT INTO camera_schema_version(version,applied_at_ms)
VALUES(1,(EXTRACT(EPOCH FROM clock_timestamp())*1000)::BIGINT)
ON CONFLICT(version) DO NOTHING;
INSERT INTO schema_version(version,applied_time_ms)
VALUES(1,(EXTRACT(EPOCH FROM clock_timestamp())*1000)::BIGINT)
ON CONFLICT(version) DO NOTHING;

COMMIT;
