BEGIN;

ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS desired_state TEXT NOT NULL DEFAULT 'stopped';
ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS analysis_enabled SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS target_infer_fps DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS algorithm_profile TEXT NOT NULL DEFAULT '';
ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS algorithms_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE camera_tasks ADD COLUMN IF NOT EXISTS callback_profile TEXT NOT NULL DEFAULT '';

UPDATE camera_tasks
SET desired_state = CASE WHEN enabled=1 THEN 'running' ELSE 'stopped' END;

CREATE TABLE IF NOT EXISTS security_alert_events (
  event_id TEXT PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES camera_tasks(task_id),
  run_id TEXT NOT NULL REFERENCES camera_task_runs(run_id),
  camera_profile TEXT NOT NULL,
  event_type TEXT NOT NULL,
  category TEXT NOT NULL,
  severity INTEGER NOT NULL CHECK (severity BETWEEN 1 AND 5),
  confidence DOUBLE PRECISION,
  track_id BIGINT,
  occurred_at_ms BIGINT NOT NULL,
  algorithm_profile TEXT NOT NULL,
  model_name TEXT NOT NULL,
  config_version TEXT NOT NULL,
  demo_classifier SMALLINT NOT NULL DEFAULT 0 CHECK (demo_classifier IN (0,1)),
  payload_json JSONB NOT NULL,
  evidence_frame_id TEXT,
  fingerprint TEXT NOT NULL,
  created_at_ms BIGINT NOT NULL,
  UNIQUE(task_id,fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_security_alert_task_time
  ON security_alert_events(task_id,occurred_at_ms DESC,event_id DESC);
CREATE INDEX IF NOT EXISTS idx_security_alert_type_time
  ON security_alert_events(event_type,occurred_at_ms DESC);

CREATE TABLE IF NOT EXISTS callback_outbox (
  outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE REFERENCES security_alert_events(event_id),
  callback_profile TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','delivering','delivered','retry','dead_letter')),
  attempt INTEGER NOT NULL DEFAULT 0,
  next_attempt_at_ms BIGINT NOT NULL,
  last_attempt_at_ms BIGINT,
  delivered_at_ms BIGINT,
  last_http_status INTEGER,
  last_error_code TEXT,
  response_body_hash TEXT,
  created_at_ms BIGINT NOT NULL,
  updated_at_ms BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_callback_outbox_due
  ON callback_outbox(status,next_attempt_at_ms,outbox_id);

CREATE TABLE IF NOT EXISTS camera_idempotency_keys (
  operation_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_digest TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  response_status INTEGER NOT NULL,
  response_json JSONB NOT NULL,
  created_at_ms BIGINT NOT NULL,
  expires_at_ms BIGINT NOT NULL,
  PRIMARY KEY(operation_scope,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_camera_idempotency_expiry
  ON camera_idempotency_keys(expires_at_ms);

INSERT INTO camera_schema_version(version,applied_at_ms)
VALUES(2,(EXTRACT(EPOCH FROM clock_timestamp())*1000)::BIGINT)
ON CONFLICT(version) DO NOTHING;

COMMIT;
